<?php
return array(
    // 微信群发每月限制
    'WEIXIN_MASS_PREMONTH' => 4, 
    // 微信群发每次用户限制
    'WEIXIN_MASS_MAXNUM' => 1000000, 
    // 企业认证页面
    'CERTIF_URL' => 'http://101.231.188.78:8083/jsxt/clientZiZhiHTML.php?&token=', 
    'qqFace' => '[
              {"id":0,"phrase":"[微笑]","url":"0.gif"},
				{"id":1,"phrase":"[撇嘴]","url":"1.gif"},
				{"id":2,"phrase":"[色]","url":"2.gif"},
				{"id":3,"phrase":"[发呆]","url":"3.gif"},
				{"id":4,"phrase":"[得意]","url":"4.gif"},
				{"id":5,"phrase":"[流泪]","url":"5.gif"},
				{"id":6,"phrase":"[害羞]","url":"6.gif"},
				{"id":7,"phrase":"[闭嘴]","url":"7.gif"},
				{"id":8,"phrase":"[睡]","url":"8.gif"},
				{"id":9,"phrase":"[大哭]","url":"9.gif"},
				{"id":10,"phrase":"[尴尬]","url":"10.gif"},
				{"id":11,"phrase":"[发怒]","url":"11.gif"},
				{"id":12,"phrase":"[调皮]","url":"12.gif"},
				{"id":13,"phrase":"[呲牙]","url":"13.gif"},
				{"id":14,"phrase":"[惊讶]","url":"14.gif"},
				{"id":15,"phrase":"[难过]","url":"15.gif"},
				{"id":16,"phrase":"[酷]","url":"16.gif"},
				{"id":17,"phrase":"[冷汗]","url":"17.gif"},
				{"id":18,"phrase":"[抓狂]","url":"18.gif"},
				{"id":19,"phrase":"[吐]","url":"19.gif"},
				{"id":20,"phrase":"[偷笑]","url":"20.gif"},
				{"id":21,"phrase":"[可爱]","url":"21.gif"},
				{"id":22,"phrase":"[白眼]","url":"22.gif"},
				{"id":23,"phrase":"[傲慢]","url":"23.gif"},
				{"id":24,"phrase":"[饥饿]","url":"24.gif"},
				{"id":25,"phrase":"[困]","url":"25.gif"},
				{"id":26,"phrase":"[惊恐]","url":"26.gif"},
				{"id":27,"phrase":"[流汗]","url":"27.gif"},
				{"id":28,"phrase":"[憨笑]","url":"28.gif"},
				{"id":29,"phrase":"[大兵]","url":"29.gif"},
				{"id":30,"phrase":"[奋斗]","url":"30.gif"},
				{"id":31,"phrase":"[咒骂]","url":"31.gif"},
				{"id":32,"phrase":"[疑问]","url":"32.gif"},
				{"id":33,"phrase":"[嘘]","url":"33.gif"},
				{"id":34,"phrase":"[晕]","url":"34.gif"},
				{"id":35,"phrase":"[折磨]","url":"35.gif"},
				{"id":36,"phrase":"[衰]","url":"36.gif"},
				{"id":37,"phrase":"[骷髅]","url":"37.gif"},
				{"id":38,"phrase":"[敲打]","url":"38.gif"},
				{"id":39,"phrase":"[再见]","url":"39.gif"},
				{"id":40,"phrase":"[擦汗]","url":"40.gif"},
				{"id":41,"phrase":"[抠鼻]","url":"41.gif"},
				{"id":42,"phrase":"[鼓掌]","url":"42.gif"},
				{"id":43,"phrase":"[糗大了]","url":"43.gif"},
				{"id":44,"phrase":"[坏笑]","url":"44.gif"},
				{"id":45,"phrase":"[左哼哼]","url":"45.gif"},
				{"id":46,"phrase":"[右哼哼]","url":"46.gif"},
				{"id":47,"phrase":"[哈欠]","url":"47.gif"},
				{"id":48,"phrase":"[鄙视]","url":"48.gif"},
				{"id":49,"phrase":"[委屈]","url":"49.gif"},
				{"id":50,"phrase":"[快哭了]","url":"50.gif"},
				{"id":51,"phrase":"[阴险]","url":"51.gif"},
				{"id":52,"phrase":"[亲亲]","url":"52.gif"},
				{"id":53,"phrase":"[吓]","url":"53.gif"},
				{"id":54,"phrase":"[可怜]","url":"54.gif"},
				{"id":55,"phrase":"[菜刀]","url":"55.gif"},
				{"id":56,"phrase":"[西瓜]","url":"56.gif"},
				{"id":57,"phrase":"[啤酒]","url":"57.gif"},
				{"id":58,"phrase":"[篮球]","url":"58.gif"},
				{"id":59,"phrase":"[乒乓]","url":"59.gif"},
				{"id":60,"phrase":"[咖啡]","url":"60.gif"},
				{"id":61,"phrase":"[饭]","url":"61.gif"},
				{"id":62,"phrase":"[猪头]","url":"62.gif"},
				{"id":63,"phrase":"[玫瑰]","url":"63.gif"},
				{"id":64,"phrase":"[凋谢]","url":"64.gif"},
				{"id":65,"phrase":"[示爱]","url":"65.gif"},
				{"id":66,"phrase":"[爱心]","url":"66.gif"},
				{"id":67,"phrase":"[心碎]","url":"67.gif"},
				{"id":68,"phrase":"[蛋糕]","url":"68.gif"},
				{"id":69,"phrase":"[闪电]","url":"69.gif"},
				{"id":70,"phrase":"[炸弹]","url":"70.gif"},
				{"id":71,"phrase":"[刀]","url":"71.gif"},
				{"id":72,"phrase":"[足球]","url":"72.gif"},
				{"id":73,"phrase":"[瓢虫]","url":"73.gif"},
				{"id":74,"phrase":"[便便]","url":"74.gif"},
				{"id":75,"phrase":"[月亮]","url":"75.gif"},
				{"id":76,"phrase":"[太阳]","url":"76.gif"},
				{"id":77,"phrase":"[礼物]","url":"77.gif"},
				{"id":78,"phrase":"[拥抱]","url":"78.gif"},
				{"id":79,"phrase":"[强]","url":"79.gif"},
				{"id":80,"phrase":"[弱]","url":"80.gif"},
				{"id":81,"phrase":"[握手]","url":"81.gif"},
				{"id":82,"phrase":"[胜利]","url":"82.gif"},
				{"id":83,"phrase":"[抱拳]","url":"83.gif"},
				{"id":84,"phrase":"[勾引]","url":"84.gif"},
				{"id":85,"phrase":"[拳头]","url":"85.gif"},
				{"id":86,"phrase":"[差劲]","url":"86.gif"},
				{"id":87,"phrase":"[爱你]","url":"87.gif"},
				{"id":88,"phrase":"[NO]","url":"88.gif"},
				{"id":89,"phrase":"[OK]","url":"89.gif"},
				{"id":90,"phrase":"[爱情]","url":"90.gif"},
				{"id":91,"phrase":"[飞吻]","url":"91.gif"},
				{"id":92,"phrase":"[跳跳]","url":"92.gif"},
				{"id":93,"phrase":"[发抖]","url":"93.gif"},
				{"id":94,"phrase":"[怄火]","url":"94.gif"},
				{"id":95,"phrase":"[转圈]","url":"95.gif"},
				{"id":96,"phrase":"[磕头]","url":"96.gif"},
				{"id":97,"phrase":"[回头]","url":"97.gif"},
				{"id":98,"phrase":"[跳绳]","url":"98.gif"},
				{"id":99,"phrase":"[挥手]","url":"99.gif"},
				{"id":100,"phrase":"[激动]","url":"100.gif"},
				{"id":101,"phrase":"[街舞]","url":"101.gif"},
				{"id":102,"phrase":"[献吻]","url":"102.gif"},
				{"id":103,"phrase":"[左太极]","url":"103.gif"},
				{"id":104,"phrase":"[右太极]","url":"104.gif"}
          ]', 
    'LOG_PATH' => LOG_PATH . 'LogAlipayServ_',  // 日志路径+文件名前缀,
    'CUSTOM_LOG_PATH' => LOG_PATH . 'LogAlipayServ_',  // 日志路径+文件名前缀,
    'ALIPAY_FWC' => array(
        'alipay_public_key_file' => CONF_PATH . "key/alipay_rsa_public_key.pem", 
        'merchant_private_key_file' => CONF_PATH . "key/rsa_private_key.pem", 
        'merchant_public_key_file' => CONF_PATH . "key/rsa_public_key.pem", 
        'charset' => "GBK", 
        'gatewayUrl' => "https://openapi.alipay.com/gateway.do", 
        'LOG_PATH' => LOG_PATH . 'LogAlipayServ_',  // 日志路径+文件名前缀,
        'CUSTOM_LOG_PATH' => LOG_PATH . 'LogAlipayServ_')); // 日志路径+文件名前缀,


